// Code generated by "stringer -type=Effect"; DO NOT EDIT.

package effect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Starving-0]
	_ = x[Poisoned-1]
}

const _Effect_name = "StarvingPoisoned"

var _Effect_index = [...]uint8{0, 8, 16}

func (i Effect) String() string {
	if i < 0 || i >= Effect(len(_Effect_index)-1) {
		return "Effect(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Effect_name[_Effect_index[i]:_Effect_index[i+1]]
}
